### PR TITLE
feat: restructure sass into modules

### PR DESCRIPTION
**Pull request by harrycresswell**
All good?

### CODE REVIEW

**Comment by benmclaren** [comment]
yeah should be fine. I wrote some mininal css but should be easy to reimplement. Its better to have this proerly structured before writin gloads of css in the old structure

**Comment by harrycresswell** [comment]
> yeah should be fine. I wrote some mininal css but should be easy to reimplement. Its better to have this proerly structured before writin gloads of css in the old structure

I’ll resolve these conflicts then

**Comment by harrycresswell** [comment]
You’re one step ahead.. nice!!

**Comment by benmclaren** [comment]
Yeah all good

**Comment by benmclaren** [comment]
I wrote like 2 css properties so its easy to put them back in

**Pull request merged**
